---
format: gfm
---

# Spatial interpolation of acute malnutrition: a quest using probability proportional to the size of the population-based survey data

To effectively combat this public health issue, enhancing the ability to tell _where_ acute malnutrition is of great concern over other areas is paramount. Possessing this information leverages the ability of programmers to prioritize limited resources - that are now getting even more shrunk amid the modern resource-constraint era.

This repository is an R implementation of a quest applying spatial interpolation modelling techniques. The quest aims to explore the usability of probability proportional to the size of the population-based survey sampling data to predict the prevalence of acute malnutrition from the observed sampling points to unobserved locations across a given survey area of interest.

## Research (quest) question:  

+ Does spatial interpolation produce reliable (precise and accurate) estimates when applied to a small-scale PPS-based survey? 

If yes: 

+ a

## Study area  
North Darfur, Sudan

## Repository Structure
+ `raw-data/`: a data frame of the input data. This is encrypted. 
+ `R/`: some handy user-defined functions.
+ `scripts/`: a set of `R` scripts. These are split into different files, based on the specific task that they execute. Run `script.R` file to implement the project workflow.  

## Reproducibility information
The repository was created in `R` version 4.4.2. This project uses the `{renv}` framework to record `R` package dependencies and versions. Packages and versions used are recorded in `renv.lock` and code used to manage dependencies is in `renv/` and other files in the root project directory. On starting an `R` session in the working directory, run `renv::restore()` to install R package dependencies.

## Data encryption  
This project uses `{cyphr}` to encrypt the raw data that lives in `data-raw/` directory. In order to be able to access and decrypt the encrypted data, the user will need to have created their own personal SSH key and make a request to be added to the project. An easy-to-grasp guide on how to make a request will be found [here](https://github.com/OxfordIHTM/cyphr-encryption-demonstration#)

## License
This repository is licensed under a GNU General Public License 3 (GPL-3).  

## Feedback
If you wish to give feedback, file an issue or seek support, kindly do so [here](https://github.com/nutspatial/ugd-karamoja-amn-interp/issues).

## Author
Tomás Zaba